### ISSUE TITLE
Latest update (from Feb 8) broke the popup

### ISSUE THREAD

**Issue by kisdma** [raingart/AutoHideDownloadsBar-extension#10]
When icon is clicked - Downloads page shows up instead of the popup

**Comment by raingart** [comment]
popup Was poorly written and was deleted.
Causes:
- There were crashes with sizing files.
- Failure of the button to control the status of the downloaded file.
- The inability to open an already downloaded file or link to it.
- The design itself was ugly.
- you cannot "resume" a broken download file

I do not have another desire to rewrite the code to fix it. Since there is a complete duplication of existing functionality in the browser.

The plugin itself is written in pure JS. And the skills available to me do not allow me to correctly implement popup. You need to use an existing framework (e.g. Vue)

And this will lead to an increase in file size at times.

The initial goal of the project is to hide the panel below. Instead of imitating the chrome: // downloads / page

You can use any of the existing extensions for this. Fortunately there are many of them. And they cope better than mine.

If you wish, you can fix popup-lib. Then add it. But I have no desire.

**Comment by kisdma** [comment]
Hi raingart, 

I'm interested in fixing those issues. I've used your extension for about a year, and haven't noticed those problems somehow :) But I noticed the disappearance of the popup right away :) Basically, my use case is just a quick way to check whether the file was downloaded correctly or failed. Would you be interested to add popup back with a reduced functionality? For, example I'm not much interested in having control over downloads through the popup (though right click to open the folder with the file was a nice feature).

Could you elaborate some more on the first three items in your list? And how to reproduce the problem? Are these issues that recently appeared with something changed in chrome or were they always there?

By the way, I think the design was fine - I liked it.

Thank you!

**Comment by raingart** [comment]
When downloading to a device and low response speed of several files. At the final stage of checking the integrity of the file, and transferring it from the device’s cache to the permanent memory. The chain determines the file size (and the following dependencies: speed, time, size) cease to be correctly determined (`NaN` or `undefined`)

Inability to determine file download speed if the final size is not defined. (Download any large file from _Google Drive_)

The download pause button sometimes crashes and does not display the current progress status.

The last stain in my patience was when I started Windows many years later and downloaded the executable file. I wanted to run it.
When I clicked on the icon of the downloaded file, it did not open. And he swayed to the sides. Why I added this crap I don’t remember. I needed to open popup and then open the directory in which the file is located. Too many extra actions.
And when the file broke I wanted to copy the link and re-download it. I pressed the right mouse button and deleted the file information. I had to look in the history from which site I downloaded it.

I wanted to fix it. I opened the source code, looked how terrible it is, nothing is clear in it.

And then I regained my sight. Why don't you need this curve popup trash? If there is a perfectly working panel from below, through which I can cancel/open files. Open directory. Everything is simple and most importantly it works.

I have had high-speed fiber optic internet for several years. Everything downloads extremely fast. The only thing that annoys is that the socket does not hide after the download is complete. This is all the extension needs to be fixed.

I separated the sound notification from the ugly browser notification window. If the file does not download, the extension will report this.

I’m silent about how much time I spent adding optional dependencies when activating some parameters during browser settings. After one of the users accused me that "_Why does the extension need to know the history of visited pages? Does it follow me and sell data?_" - it struck me. But who needs links to your visited porn sites? I had to make excuses and resubmit the extension. In order to elevate in a second that during synchronization they (additional permissions) are not transferred and break extensions. I had to refuse to synchronize settings. And move them to the local area. Which led to failures when updating different versions of extensions for users.
After that, I turned off the ability to write about problems on the extension page. Only on github. This filters illiterate requests. The harder the path, the less it will go. And there is a chance that I will write a person with minimal knowledge.

**If you really want to return popup, you can download the locally old version and install it:** https://www.crx4chrome.com/history/89989/
If it satisfies your fasting. Sync settings and so does not work. You do not lose any functionality.

I'm sick of it all. The older I get, the less tolerant I get. If something annoys me or does not like me, I will already get rid of it than I will correct it. I don’t want to waste a lot of time sorting out, fixing and then discovering that it is working incorrectly or has broken.

I was generally going to remove the extension. But in half a minute of searching, I did not find the extension that hid the panel from the bottom after the download was completed. But not all the time.

I wrote a lot. But I have no desire to modify the extension. But neither can I justify the reasons and cannot answer you either. You spent your time and wrote to me.

Best regards. Raingart.

ps the exact phrase -- _"I’m Getting Too Old For This Shit"_ - Stripes 1981
