### ISSUE TITLE
"Show notification" not working

### ISSUE THREAD

**Issue by AkazaRenn** [raingart/AutoHideDownloadsBar-extension#11]
Tested on Chromium Edge build 80.0.361.109.

**Comment by raingart** [comment]
I don’t have Windows OS to test it.
Try this bild:
[chrome_bar.zip](https://github.com/raingart/AutoHideDownloadsBar-extension/files/4436478/chrome_bar.zip)

There are two methods of notification inference
- web api
- chrome api

You can switch them on
file `/js/background.js `
line `98-133`

Write which one has earned

**Comment by AkazaRenn** [comment]
@raingart neither of them worked

**Comment by raingart** [comment]
Sorry, I can’t fix the error then. I'm too lazy to install the OS and test for this.

These two methods are the only ones that allow to snow notification in the browser.
It would be nice to see what is displayed in the console.

I think the reason is that the notification is disabled in the browser itself:
https://techcommunity.microsoft.com/t5/discussions/edge-chromium-not-in-notification-app-list/m-p/417759
