### ISSUE TITLE
clicking on the icon does not open downloads tab

### ISSUE THREAD

**Issue by mark-hahn** [raingart/AutoHideDownloadsBar-extension#13]
As the subject says, I selected tab for clicking on icon and it doesn't work.  It worked before I reinstalled windows and chrome.

**Comment by raingart** [comment]
This is because the extension uses optional dependencies. But they do not carry over to new instances of the browser.

I answered in one of the reviews. The bottom line is that you can't "look safe" for noobs and have sync.

NewtomicFeb 14, 2021
_I like this one, and the sound option it a very welcome plus, could be even better if syncs options between computers._

Reply
ori onFeb 14, 2021
_Earlier versions had full sync. But some users started to complain that the extension needs too many rights (reading history, notification) "Why are they needed? You will steal history and send ads!". I had to use optional permission, which is not available for synchronization._

**How to fix?**
Just change the opening settings. An access request should appear

Idk, I probably won't update the extension. Unique solution that comes to my mind. When updating, remove the option to select the open window type. But I already see how another not happy will write that he found a bug.

Sorry, **but the users themselves are to blame.**

Initially, everything worked. But no, there is bound be one user so important that his list of visited porn pages will steal a godforsaken extension.

**What they wanted and got.**
And the fact that it works through one place, thank the developers (chrome google) who flapped in email: to immediately remove all unimportant access rights to the opional ones. But at the same time, without providing sane ways to the export optional access config state between browser instances
