### ISSUE TITLE
Downloads Bar Completely White

### ISSUE THREAD

**Issue by timikesmarky** [raingart/AutoHideDownloadsBar-extension#6]
Hello,

Since a few days, the downloads bar is completely white, I can't see any text. Just borders.

**Comment by timikesmarky** [comment]
Fixed, theme issue.

**Comment by raingart** [comment]
You can open an error output console on the page:
extension://gkmndgjgpolmikgnipipfekglbbgjcel/html/background.html

It just works for me. Perhaps a local failure.

Try reinstalling. 
And throw the version of your browser.

UPD: I see it fixed, if there are problems or suggestions please write, we will try to solve them.
Good luck!

**Comment by timikesmarky** [comment]
It seems to be a problem with "Just Black" chrome theme.

**Comment by raingart** [comment]
@timikesmarky i know what the error is.
The extension registers all active downloads. They are considered active until there is no "_complete_" or "_pause_" status.

When installing extensions or themes, there are cases when you need confirmation to start the installation (another state is active but waiting). It should be displayed in `chrome://downloads/` with the active button.

This happens when you try to download/install one and the same extension twice. The last request is accepted. But the first burns as active.

I will try to fix this in the next version.
