### ISSUE TITLE
Honor dark mode in Windows

### ISSUE THREAD

**Issue by FadeMind** [raingart/AutoHideDownloadsBar-extension#8]
Hi, please honor dark theming. Current looks:
![s](https://i.imgur.com/uGfaPs0.png)

**Comment by raingart** [comment]
No idea how to define in the extension enable dark mode or not. 

Sorry, if you know the extensions in which it is implemented or how to implement it then write. 

Since the user often sees the settings window once. I know about this problem, but it is insignificant in comparison with others. Bad extension architecture. And problems with the fact that when you transfer synchronization settings are lost optional permissions.

So it turns out that we all use existing shit. Since such extensions are much more (written in nodejs / vue), they use even more resources. At the same time, they have even more miserable functionality.
